version: '3.9'
services: 
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - /root/data/:/var/lib/mysql:rw
      - ./DataBase/mysql-5.x/:/database/
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mya2billing 
      MYSQL_USER: a2billinguser
      MYSQL_PASSWORD: a2billing
    #labels:
    #  - traefik.enable=false
    networks:
      - traefik
  asterisk:
    image: asterisk
    restart: always
    container_name: asterisk
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.asterisk.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.asterisk.entrypoints=asterisk"
      - "traefik.tcp.routers.asterisk.service=asterisk"
      - "traefik.tcp.services.asterisk.loadbalancer.server.port=5060"
     
    networks:
      - traefik
    depends_on:
      - mysql
  admin:
    image: admin
    restart: always
    container_name: admin
    labels:
      - "traefik.backend=admin"
      - "traefik.http.routers.admin.rule=Host(`www.voip.com`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.admin.tls=false"
      - "traefik.port=80"
    networks:
      - traefik
     
    depends_on:
      - mysql
  customer:
    image: customer
    restart: always
    container_name: customer
    labels:
      - "traefik.backend=customer"
      - "traefik.http.routers.customer.rule=Host(`www.voip.com`) && PathPrefix(`/customer`)"
      - "traefik.http.routers.customer.tls=false"
      - "traefik.port=80"
    networks:
      - traefik
    depends_on:
      - mysql
  traefik:
    image: traefik:v2.2
    restart: always
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/traefik_dynamic.toml:/traefik_dynamic.toml
    networks:
      - traefik
      
    ports:
    - "80:80"
    - "5060:5060/tcp"
    - "5060:5060/udp"
    - "8080:8080"
networks:
  traefik:
    external: true
 

