version: '3.9'
services: 
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - /root/data/:/var/lib/mysql:rw
      - ./DataBase/mysql-5.x/:/database/
      - ./a2billing.conf:/etc/a2billing.conf
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mya2billing 
      MYSQL_USER: a2billinguser
      MYSQL_PASSWORD: a2billing
    labels:
      - traefik.enable=false
    networks:
      - web
  asterisk:
    image: asterisk
    restart: always
    container_name: asterisk
    networks:
      - web
    depends_on:
      - mysql
  admin:
    image: admin
    restart: always
    container_name: admin
    labels:
      - traefik.http.routers.admin.rule=Host(`admin.voip.com`)
      - traefik.port=80
    
    networks:
      - web
    depends_on:
      - mysql
  customer:
    image: customer
    restart: always
    container_name: customer
    labels:
      - traefik.http.routers.customer.rule=Host(`customer.voip.com`)
      - traefik.port=80
    
    networks:
      - web
    depends_on:
      - mysql
  traefik:
    image: traefik:v2.2
    restart: always
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/traefik_dynamic.toml:/traefik_dynamic.toml

    networks:
      - web
    ports:
    - "80:80"
    - "5060:5060"

networks:
  web:
    driver: bridge
    name: web

