[entryPoints]
 
[entryPoints.web]
 
address = ":80"
  
[entryPoints.asterisk]
 
address = ":5060"

[api]
dashboard = true

[providers.docker]
 
watch = true
 
network = "web"
 
[providers.file]
 
filename = "traefik_dynamic.toml"

