[log]
  level = "DEBUG"
  filePath = "log-file.log"

[accessLog]
  filePath =  "log-access.log"
  



[api]
  dashboard = true
  debug = true
  insecure = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.asterisk]
    address = ":5060"
  [entryPoints.udp-asterisk]
    address = ":5060/udp" 
    
[providers.file]
  filename = "traefik_dynamic.toml"

[providers.docker]   
  watch = true
  network = "traefik"
   


