[http.middlewares.simpleAuth.basicAuth]
 
users = [
 
"admin:admin:$apr1$tNRh/vr6$Ick9R9pGk4nbaNGd0L7QY/"
 
]
 
[http.routers.api]
 
rule = "Host(`monitor.voip.com`)"
 
entrypoints = ["web"]
 
middlewares = ["simpleAuth"]
 
service = "api@internal"
 
